---
# Dock items to remove.
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - Keynote
  - Numbers
  - Pages
  - 'App Store'
  - 'System Settings'
  - Downloads

# Dock items to add. `pos` parameter is optional and will place the Dock item
dockitems_persist:
  - name: "Finder"
    path: "/System/Library/CoreServices/Finder.app/"
    pos: 0
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 1
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 2
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 3
  - name: "Kitty"
    path: "/Applications/kitty.app/"
    pos: 4
  - name: ""
    type: "spacer"
