---
- name: Install dockutil
  community.general.homebrew:
    name: dockutil
    state: present

- name: Remove listed items from dock
  ansible.builtin.include_tasks: dock-remove.yml
  loop: "{{ dockitems_remove }}"

- name: Add listed items to dock
  ansible.builtin.include_tasks: dock-add.yml
  loop: "{{ dockitems_persist }}"

- name: Ensure dock items are in the expected position
  ansible.builtin.include_tasks: dock-position.yml
  when:
    - item.pos is defined
    - item.pos > 0
  loop: "{{ dockitems_persist }}"

- name: Set autohide dock to true
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

- name: Disable dock bouncing
  community.general.osx_defaults:
    domain: com.apple.dock
    key: no-bouncing
    type: bool
    value: true
    state: present

- name: Set dock app opening effect
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: scale
    state: present

- name: Set dock minimize to app flag
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
    state: present

- name: Set tile size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 55
    state: present
