---
- name: Make Finder open the Home directory on start
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfHm" # Home
    state: present

- name: Change current search scope for all new searches to the current directory
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
    state: present

- name: Change finder view to list by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlvs"
    state: present

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present

- name: Keep folders on top when sorting by name
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
    state: present

- name: Toggle status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present

- name: Toggle bottom path bar by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    state: present

- name: Show the ~/Library folder in finder
  ansible.builtin.shell: >
    chflags nohidden ~/Library
  changed_when: false
  become: true

- name: Display all files
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
