---
- name: Enable Firewall
  ansible.builtin.command:
    cmd: defaults -currentHost write /Library/Preferences/com.apple.alf globalstate -bool true
  become: true

- name: Enable stealth mode
  block:
    - name: Check stealh mode status
      ansible.builtin.command:
        cmd: defaults -currentHost read /Library/Preferences/com.apple.alf stealthenabled
      register: firewall_stealth_enabled
      changed_when: firewall_stealth_enabled != 1
      become: true

    - name: Enable stealth Mode
      ansible.builtin.command:
        cmd: defaults write /Library/Preferences/com.apple.alf stealthenabled -bool true
      when: firewall_stealth_enabled != 1
      become: true

