R_bin_path: /usr/local/bin/Rscript
CRAN_MIRROR: https://cran.irsn.fr

CRAN_packages:
  - abind
  - askpass
  - backports
  - base64enc
  - bayestestR
  - bestNormalize
  - bit
  - bit64
  - blob
  - brio
  - broom
  - bslib
  - butcher
  - cachem
  - callr
  - car
  - carData
  - cellranger
  - checkmate
  - cli
  - clipr
  - clock
  - colorspace
  - conflicted
  - corrplot
  - covr
  - cpp11
  - crayon
  - curl
  - data.table
  - datawizard
  - DBI
  - dbplyr
  - deming
  - Deriv
  - desc
  - diagram
  - diffobj
  - digest
  - doParallel
  - doRNG
  - dplyr
  - dtplyr
  - effectsize
  - ellipsis
  - emmeans
  - estimability
  - evaluate
  - fansi
  - farver
  - fastmap
  - fontawesome
  - forcats
  - foreach
  - Formula
  - fs
  - future
  - future.apply
  - gargle
  - generics
  - ggeffects
  - ggplot2
  - globals
  - glue
  - googledrive
  - googlesheets4
  - gower
  - gridExtra
  - gtable
  - hardhat
  - haven
  - highr
  - Hmisc
  - hms
  - htmlTable
  - htmltools
  - htmlwidgets
  - httr
  - ids
  - insight
  - ipred
  - isoband
  - iterators
  - jquerylib
  - jsonlite
  - knitr
  - labeling
  - LambertW
  - lamW
  - lava
  - lazyeval
  - lifecycle
  - listenv
  - lme4
  - lmerTest
  - lobstr
  - lpSolve
  - lsmeans
  - lubridate
  - magrittr
  - Matrix
  - MatrixModels
  - mediation
  - memoise
  - mime
  - minqa
  - mnormt
  - mockery
  - modelr
  - munsell
  - mvtnorm
  - nloptr
  - nortest
  - numDeriv
  - openssl
  - parallelly
  - parameters
  - pbkrtest
  - performance
  - pillar
  - pkgbuild
  - pkgconfig
  - pkgload
  - plyr
  - praise
  - prettyunits
  - processx
  - prodlim
  - progress
  - progressr
  - pryr
  - ps
  - psych
  - purrr
  - quantreg
  - R6
  - ragg
  - rappdirs
  - RColorBrewer
  - Rcpp
  - RcppEigen
  - RcppParallel
  - readr
  - readxl
  - recipes
  - rematch
  - rematch2
  - reprex
  - reshape
  - reshape2
  - rex
  - rlang
  - rmarkdown
  - rngtools
  - rprojroot
  - rsq
  - rstatix
  - rstudioapi
  - rvest
  - sandwich
  - sass
  - scales
  - selectr
  - shape
  - sjlabelled
  - sjmisc
  - sjPlot
  - sjstats
  - SparseM
  - SQUAREM
  - stringi
  - stringr
  - sys
  - systemfonts
  - testthat
  - textshaping
  - tibble
  - tidyr
  - tidyselect
  - tidyverse
  - timechange
  - timeDate
  - tinytex
  - tzdb
  - utf8
  - uuid
  - vctrs
  - viridis
  - viridisLite
  - vroom
  - waldo
  - withr
  - xfun
  - xml2
  - yaml
  - zoo
  - base
  - boot
  - class
  - cluster
  - codetools
  - compiler
  - datasets
  - foreign
  - graphics
  - grDevices
  - grid
  - KernSmooth
  - lattice
  - MASS
  - Matrix
  - methods
  - mgcv
  - nlme
  - nnet
  - parallel
  - rpart
  - spatial
  - splines
  - stats
  - stats4
  - survival
  - tcltk
  - tools
  - utils
