---
- name: Add the Hashicorp Homebrew tap
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install terraform
  community.general.homebrew:
    name: hashicorp/tap/terraform
    state: latest

# A static analysis tool for critical terraform configuration
- name: Install tfsec
  community.general.homebrew:
    name: tfsec
    state: latest
  
