---
- name: "Install tmux"
  community.general.homebrew:
    name: tmux
    state: present

- name: "Install TPM"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "Ensure the tmux config directory exists"
  file:
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: "directory"
    mode: 0644

- name: "Copy tmux config file"
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    mode: 0644

- name: "Copy tmux theme file"
  copy:
    src: "{{ role_path }}/files/theme.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    mode: 0644

