---
- name: "Install tmux"
  community.general.homebrew:
    name: tmux
    state: present

- name: "Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "Copy tmux config file"
  ansible.builtin.copy:
    src: .tmux.config
    dest: "{{ ansible_user_dir }}/.config/"
    mode: 0644

- name: "Copy tmux theme file"
  ansible.builtin.copy:
    src: .tmux-theme.conf
    dest: "{{ ansible_user_dir }}/.config/"
    mode: 0644

