---
- name: Install tmux
  dnf:
    name: tmux
    state: present

- name: Install TPM
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Copy tmux config file
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: 0644

- name: Copy tmux theme file
  copy:
    src: "{{ role_path }}/files/.tmux-theme.conf"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: 0644
