---
- name: Install neovim dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - ripgrep
    - codespell
    - ansible-lint

- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: latest

- name: Setup config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Create symlink to role files directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
