---
- name: Install neovim dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - ripgrep
    - codespell
    - ansible-lint
    - node

- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: latest

- name: Setup config folder
  file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Copy nvim configuration files
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/.config/nvim/"
