---
- name: Run Mac OS tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - nvim
    - neovim

- name: Run Fedora tasks
  ansible.builtin.import_tasks: fedora.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - nvim
    - neovim
